import type { RedactionRule } from 'services/redaction/redaction.types.ts';

export const CI_PACKAGE_MANAGERS_RULES: readonly RedactionRule[] = [
  {
    id: 'npm-token',
    description: 'npm access token (npm_)',
    pattern: /\bnpm_[A-Za-z0-9]{36,}\b/g,
    replacement: '[REDACTED:npm-token]',
    stage: 1,
  },
  {
    id: 'pypi-token',
    description: 'PyPI API token (pypi-)',
    pattern: /\bpypi-[A-Za-z0-9_-]{50,}\b/g,
    replacement: '[REDACTED:pypi-token]',
    stage: 1,
  },
  {
    id: 'circleci-personal-token',
    description: 'CircleCI personal access token (CCIPAT_)',
    pattern: /\bCCIPAT_[A-Za-z0-9_]{32,}\b/g,
    replacement: '[REDACTED:circleci-personal-token]',
    stage: 1,
  },
  {
    id: 'postman-api-key',
    description: 'Postman API key (PMAK-)',
    pattern: /\bPMAK-[a-fA-F0-9]{24}-[a-fA-F0-9]{34}\b/g,
    replacement: '[REDACTED:postman-api-key]',
    stage: 1,
  },
  {
    id: 'pulumi-access-token',
    description: 'Pulumi access token (pul-)',
    pattern: /\bpul-[a-f0-9]{40}\b/g,
    replacement: '[REDACTED:pulumi-access-token]',
    stage: 1,
  },
  {
    id: 'circleci-context-token',
    description: 'CircleCI context API token (CCI_)',
    pattern: /\bCCI_[A-Za-z0-9]{40,}\b/g,
    replacement: '[REDACTED:circleci-context-token]',
    stage: 1,
  },
  {
    id: 'travis-ci-token',
    description: 'Travis CI personal access token (22 alnum after TRAVIS keyword)',
    pattern: /(TRAVIS[_-]?(?:CI[_-]?)?(?:API[_-]?)?TOKEN\s*[:=]\s*)["']?[A-Za-z0-9]{22}["']?/gi,
    replacement: '$1[REDACTED:travis-ci-token]',
    stage: 2,
  },
  {
    id: 'buildkite-agent-token',
    description: 'Buildkite agent registration token (40 alnum after BUILDKITE keyword)',
    pattern: /(BUILDKITE[_-]?(?:AGENT[_-]?)?TOKEN\s*[:=]\s*)["']?[A-Za-z0-9]{40}["']?/gi,
    replacement: '$1[REDACTED:buildkite-agent-token]',
    stage: 2,
  },
  {
    id: 'drone-ci-token',
    description: 'Drone CI personal token (32 alnum after DRONE keyword)',
    pattern: /(DRONE[_-]?(?:TOKEN|RPC[_-]?SECRET)\s*[:=]\s*)["']?[A-Za-z0-9]{32}["']?/gi,
    replacement: '$1[REDACTED:drone-ci-token]',
    stage: 2,
  },
  {
    id: 'cargo-registry-token',
    description: 'Cargo / crates.io registry token (cio + 32 hex)',
    pattern: /\bcio[a-f0-9]{32}\b/g,
    replacement: '[REDACTED:cargo-registry-token]',
    stage: 1,
  },
  {
    id: 'rubygems-api-key',
    description: 'RubyGems API key (rubygems_ + 48 hex)',
    pattern: /\brubygems_[a-f0-9]{48}\b/g,
    replacement: '[REDACTED:rubygems-api-key]',
    stage: 1,
  },
  {
    id: 'nuget-api-key',
    description: 'NuGet API key (oy2 + 43 alnum)',
    pattern: /\boy2[a-z0-9]{43}\b/g,
    replacement: '[REDACTED:nuget-api-key]',
    stage: 1,
  },
  {
    id: 'jenkins-api-token',
    description: 'Jenkins API token (32 hex after jenkins keyword)',
    pattern: /(jenkins[\s_-]+(?:api[\s_-]+)?token\s*[:=]?\s*)["']?11[a-f0-9]{32}["']?/gi,
    replacement: '$1[REDACTED:jenkins-api-token]',
    stage: 2,
  },
  {
    id: 'codecov-upload-token',
    description: 'Codecov upload token (UUID after CODECOV keyword)',
    pattern:
      /(CODECOV[_-]?(?:TOKEN|UPLOAD[_-]?TOKEN)\s*[:=]\s*)["']?[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}["']?/gi,
    replacement: '$1[REDACTED:codecov-upload-token]',
    stage: 2,
  },
  {
    id: 'snyk-token',
    description: 'Snyk API token (UUID after SNYK keyword)',
    pattern:
      /(SNYK[_-]?(?:TOKEN|API[_-]?KEY)\s*[:=]\s*)["']?[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}["']?/gi,
    replacement: '$1[REDACTED:snyk-token]',
    stage: 2,
  },
];
