import type { RedactionRule } from 'services/redaction/redaction.types.ts';

export const CLOUD_PROVIDERS_RULES: readonly RedactionRule[] = [
  {
    id: 'aws-access-key',
    description: 'AWS Access Key ID (AKIA, ASIA, ABIA, ACCA, A3T*)',
    pattern: /\b(?:AKIA|ASIA|ABIA|ACCA|A3T[A-Z0-9])[A-Z0-9]{16}\b/g,
    replacement: '[REDACTED:aws-access-key]',
    stage: 1,
  },
  {
    id: 'google-api-key',
    description: 'Google API key (AIza)',
    pattern: /\bAIza[0-9A-Za-z_-]{35}\b/g,
    replacement: '[REDACTED:google-api-key]',
    stage: 1,
  },
  {
    id: 'google-oauth-access-token',
    description: 'Google OAuth access token (ya29.)',
    pattern: /\bya29\.[0-9A-Za-z_-]{20,}\b/g,
    replacement: '[REDACTED:google-oauth-access-token]',
    stage: 1,
  },
  {
    id: 'google-oauth-client-id',
    description: 'Google OAuth client ID',
    pattern: /\b\d+-[a-z0-9_]{32}\.apps\.googleusercontent\.com\b/g,
    replacement: '[REDACTED:google-oauth-client-id]',
    stage: 1,
  },
  {
    id: 'firebase-cloud-messaging-key',
    description: 'Firebase Cloud Messaging server key',
    pattern: /\bAAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140,}\b/g,
    replacement: '[REDACTED:firebase-cloud-messaging-key]',
    stage: 1,
  },
  {
    id: 'digitalocean-token',
    description: 'DigitalOcean access / OAuth / refresh token (do[oprt]_v1_)',
    pattern: /\bdo[oprt]_v1_[a-f0-9]{60,}\b/g,
    replacement: '[REDACTED:digitalocean-token]',
    stage: 1,
  },
  {
    id: 'aws-secret-context',
    description: 'AWS secret access key value following the canonical keyword (Stage 2)',
    pattern: /(\baws_secret_access_key\s*[:=]\s*)["']?([A-Za-z0-9/+]{40})["']?/gi,
    replacement: '$1[REDACTED:aws-secret-key]',
    stage: 2,
  },
  {
    id: 'aws-mws-auth-token',
    description: 'AWS Marketplace Web Service auth token (amzn.mws.UUID)',
    pattern: /\bamzn\.mws\.[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b/g,
    replacement: '[REDACTED:aws-mws-auth-token]',
    stage: 1,
  },
  {
    id: 'aws-session-token-context',
    description: 'AWS session token value following the canonical keyword (Stage 2)',
    pattern: /(\baws_session_token\s*[:=]\s*)["']?[A-Za-z0-9/+=]{100,}["']?/gi,
    replacement: '$1[REDACTED:aws-session-token]',
    stage: 2,
  },
  {
    id: 'azure-storage-account-key',
    description: 'Azure storage account key (88-char base64 after AccountKey=)',
    pattern: /(AccountKey\s*=\s*)[A-Za-z0-9+/]{86}==/g,
    replacement: '$1[REDACTED:azure-storage-account-key]',
    stage: 1,
  },
  {
    id: 'azure-shared-access-signature',
    description: 'Azure shared access signature (sig= URL parameter)',
    pattern: /[?&]sig=[A-Za-z0-9%]{40,}/g,
    replacement: '?sig=[REDACTED:azure-shared-access-signature]',
    stage: 1,
  },
  {
    id: 'azure-ad-client-secret-context',
    description: 'Azure AD client secret value following the canonical keyword (Stage 2)',
    pattern: /(AZURE[_-]?CLIENT[_-]?SECRET\s*[:=]\s*)["']?[A-Za-z0-9~._-]{34,}["']?/gi,
    replacement: '$1[REDACTED:azure-ad-client-secret]',
    stage: 2,
  },
  {
    id: 'cloudflare-api-token',
    description: 'Cloudflare API token (40-char base64url after CF_API_TOKEN keyword)',
    pattern: /(CF[_-]?API[_-]?(?:TOKEN|KEY)\s*[:=]\s*)["']?[A-Za-z0-9_-]{40}["']?/gi,
    replacement: '$1[REDACTED:cloudflare-api-token]',
    stage: 2,
  },
  {
    id: 'cloudflare-global-api-key',
    description: 'Cloudflare global API key (37 hex after CLOUDFLARE keyword)',
    pattern: /(CLOUDFLARE[_-]?(?:GLOBAL[_-]?)?API[_-]?KEY\s*[:=]\s*)["']?[a-f0-9]{37}["']?/gi,
    replacement: '$1[REDACTED:cloudflare-global-api-key]',
    stage: 2,
  },
  {
    id: 'linode-personal-access-token',
    description: 'Linode personal access token (64 hex after LINODE keyword)',
    pattern: /(LINODE[_-]?(?:CLI[_-]?)?TOKEN\s*[:=]\s*)["']?[a-f0-9]{64}["']?/gi,
    replacement: '$1[REDACTED:linode-personal-access-token]',
    stage: 2,
  },
  {
    id: 'vultr-api-key',
    description: 'Vultr API key (36 alphanumeric after VULTR keyword)',
    pattern: /(VULTR[_-]?API[_-]?KEY\s*[:=]\s*)["']?[A-Z0-9]{36}["']?/gi,
    replacement: '$1[REDACTED:vultr-api-key]',
    stage: 2,
  },
  {
    id: 'oracle-cloud-api-key',
    description: 'Oracle Cloud API key OCID (ocid1.user.oc1)',
    pattern: /\bocid1\.(?:user|tenancy|compartment|key)\.oc[12]\.\.[a-z0-9]{40,}\b/g,
    replacement: '[REDACTED:oracle-cloud-api-key]',
    stage: 1,
  },
  {
    id: 'ibm-cloud-iam-key',
    description: 'IBM Cloud IAM API key (44 char after IBM keyword)',
    pattern:
      /(IBM[_-]?CLOUD[_-]?(?:IAM[_-]?)?(?:API[_-]?)?KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{44}["']?/gi,
    replacement: '$1[REDACTED:ibm-cloud-iam-key]',
    stage: 2,
  },
];
