import type { RedactionRule } from 'services/redaction/redaction.types.ts';

export const LLM_PROVIDERS_RULES: readonly RedactionRule[] = [
  {
    id: 'anthropic-api-key',
    description: 'Anthropic API key (sk-ant-...)',
    pattern: /\bsk-ant-[A-Za-z0-9_-]{20,}\b/g,
    replacement: '[REDACTED:anthropic-api-key]',
  },
  {
    id: 'openrouter-api-key',
    description: 'OpenRouter API key (sk-or-v1-...)',
    pattern: /\bsk-or-v1-[A-Za-z0-9]{40,}\b/g,
    replacement: '[REDACTED:openrouter-api-key]',
  },
  {
    id: 'deepseek-api-key',
    description: 'DeepSeek API key (anchored on DEEPSEEK keyword; shape overlaps with OpenAI)',
    pattern: /(DEEPSEEK[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{32,}["']?/g,
    replacement: '$1[REDACTED:deepseek-api-key]',
  },
  {
    id: 'openai-api-key',
    description: 'OpenAI API key (sk-, sk-proj-, sk-svcacct-)',
    pattern: /\bsk-(?!ant-)(?:proj-|svcacct-)?[A-Za-z0-9_-]{32,}\b/g,
    replacement: '[REDACTED:openai-api-key]',
  },
  {
    id: 'huggingface-token',
    description: 'Hugging Face access token (hf_...)',
    pattern: /\bhf_[A-Za-z0-9]{34,}\b/g,
    replacement: '[REDACTED:huggingface-token]',
  },
  {
    id: 'replicate-token',
    description: 'Replicate API token (r8_...)',
    pattern: /\br8_[A-Za-z0-9]{37,}\b/g,
    replacement: '[REDACTED:replicate-token]',
  },
  {
    id: 'cohere-api-key',
    description: 'Cohere API key (co_...)',
    pattern: /\bco_[A-Za-z0-9]{40,}\b/g,
    replacement: '[REDACTED:cohere-api-key]',
  },
  {
    id: 'groq-api-key',
    description: 'Groq API key (gsk_...)',
    pattern: /\bgsk_[A-Za-z0-9]{40,}\b/g,
    replacement: '[REDACTED:groq-api-key]',
  },
  {
    id: 'xai-grok-api-key',
    description: 'xAI Grok API key (xai-...)',
    pattern: /\bxai-[A-Za-z0-9]{60,}\b/g,
    replacement: '[REDACTED:xai-grok-api-key]',
  },
  {
    id: 'fireworks-api-key',
    description: 'Fireworks AI API key (fw_...)',
    pattern: /\bfw_[A-Za-z0-9]{20,}\b/g,
    replacement: '[REDACTED:fireworks-api-key]',
  },
  {
    id: 'perplexity-api-key',
    description: 'Perplexity AI API key (pplx-...)',
    pattern: /\bpplx-[A-Za-z0-9]{40,}\b/g,
    replacement: '[REDACTED:perplexity-api-key]',
  },
  {
    id: 'voyage-api-key',
    description: 'Voyage AI API key (pa-...)',
    pattern: /\bpa-[A-Za-z0-9_-]{40,}\b/g,
    replacement: '[REDACTED:voyage-api-key]',
  },
  {
    id: 'cerebras-api-key',
    description: 'Cerebras Cloud API key (csk-...)',
    pattern: /\bcsk-[A-Za-z0-9_-]{40,}\b/g,
    replacement: '[REDACTED:cerebras-api-key]',
  },
  {
    id: 'anyscale-api-key',
    description: 'Anyscale Endpoints API key (esecret_...)',
    pattern: /\besecret_[A-Za-z0-9_-]{32,}\b/g,
    replacement: '[REDACTED:anyscale-api-key]',
  },
  {
    id: 'runpod-api-key',
    description: 'RunPod API key (rpa_...)',
    pattern: /\brpa_[A-Za-z0-9]{32,}\b/g,
    replacement: '[REDACTED:runpod-api-key]',
  },
  {
    id: 'nvidia-nim-api-key',
    description: 'NVIDIA NGC / NIM / Build API key (nvapi-...)',
    pattern: /\bnvapi-[A-Za-z0-9_-]{40,}\b/g,
    replacement: '[REDACTED:nvidia-nim-api-key]',
  },
  {
    id: 'mistral-api-key',
    description: 'Mistral API key (32-char alphanumeric after MISTRAL keyword)',
    pattern: /(MISTRAL[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9]{32}["']?/g,
    replacement: '$1[REDACTED:mistral-api-key]',
  },
  {
    id: 'together-ai-api-key',
    description: 'Together AI API key (64 hex after TOGETHER keyword)',
    pattern: /(TOGETHER[_A-Z]*KEY\s*[:=]\s*)["']?[a-f0-9]{64}["']?/g,
    replacement: '$1[REDACTED:together-ai-api-key]',
  },
  {
    id: 'azure-openai-api-key',
    description: 'Azure OpenAI API key (32-char hex after AZURE_OPENAI keyword)',
    pattern: /(AZURE_OPENAI[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9]{32}["']?/g,
    replacement: '$1[REDACTED:azure-openai-api-key]',
  },
  {
    id: 'gemini-api-key',
    description: 'Google Gemini API key (anchored on GEMINI keyword)',
    pattern: /(GEMINI[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{30,}["']?/g,
    replacement: '$1[REDACTED:gemini-api-key]',
  },
  {
    id: 'ai21-api-key',
    description: 'AI21 Labs API key (32-char alnum after AI21 keyword)',
    pattern: /(AI21[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9]{32}["']?/g,
    replacement: '$1[REDACTED:ai21-api-key]',
  },
  {
    id: 'aleph-alpha-api-key',
    description: 'Aleph Alpha API key (anchored on ALEPH_ALPHA keyword)',
    pattern: /(ALEPH_ALPHA[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{30,}["']?/g,
    replacement: '$1[REDACTED:aleph-alpha-api-key]',
  },
  {
    id: 'deepinfra-api-key',
    description: 'DeepInfra API key (anchored on DEEPINFRA keyword)',
    pattern: /(DEEPINFRA[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{32,}["']?/g,
    replacement: '$1[REDACTED:deepinfra-api-key]',
  },
  {
    id: 'modal-api-key',
    description: 'Modal Labs API token (anchored on MODAL keyword)',
    pattern: /(MODAL[_A-Z]*(?:TOKEN|KEY|SECRET)\s*[:=]\s*)["']?[A-Za-z0-9_.-]{20,}["']?/g,
    replacement: '$1[REDACTED:modal-api-key]',
  },
  {
    id: 'lambda-labs-api-key',
    description: 'Lambda Labs API key (anchored on LAMBDA keyword)',
    pattern: /(LAMBDA[_A-Z]*(?:CLOUD|LABS)?[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{32,}["']?/g,
    replacement: '$1[REDACTED:lambda-labs-api-key]',
  },
  {
    id: 'baseten-api-key',
    description: 'Baseten API key (anchored on BASETEN keyword)',
    pattern: /(BASETEN[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_.-]{20,}["']?/g,
    replacement: '$1[REDACTED:baseten-api-key]',
  },
  {
    id: 'sambanova-api-key',
    description: 'SambaNova API key (anchored on SAMBANOVA keyword)',
    pattern: /(SAMBANOVA[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{30,}["']?/g,
    replacement: '$1[REDACTED:sambanova-api-key]',
  },
  {
    id: 'lepton-api-key',
    description: 'Lepton AI API token (anchored on LEPTON keyword)',
    pattern: /(LEPTON[_A-Z]*(?:TOKEN|KEY)\s*[:=]\s*)["']?[A-Za-z0-9_-]{30,}["']?/g,
    replacement: '$1[REDACTED:lepton-api-key]',
  },
  {
    id: 'inflection-api-key',
    description: 'Inflection AI API key (anchored on INFLECTION keyword)',
    pattern: /(INFLECTION[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{30,}["']?/g,
    replacement: '$1[REDACTED:inflection-api-key]',
  },
  {
    id: 'novita-api-key',
    description: 'Novita AI API key (anchored on NOVITA keyword)',
    pattern: /(NOVITA[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9_-]{32,}["']?/g,
    replacement: '$1[REDACTED:novita-api-key]',
  },
  {
    id: 'hyperbolic-api-key',
    description: 'Hyperbolic AI API key (anchored on HYPERBOLIC keyword)',
    pattern: /(HYPERBOLIC[_A-Z]*KEY\s*[:=]\s*)["']?[A-Za-z0-9._-]{30,}["']?/g,
    replacement: '$1[REDACTED:hyperbolic-api-key]',
  },
];
