import type { RedactionRule } from 'services/redaction/redaction.types.ts';

export const SAAS_TOOLS_RULES: readonly RedactionRule[] = [
  {
    id: 'notion-token',
    description: 'Notion integration secret (secret_)',
    pattern: /\bsecret_[A-Za-z0-9]{43,}\b/g,
    replacement: '[REDACTED:notion-token]',
  },
  {
    id: 'linear-api-key',
    description: 'Linear API key (lin_api_)',
    pattern: /\blin_api_[A-Za-z0-9]{32,}\b/g,
    replacement: '[REDACTED:linear-api-key]',
  },
  {
    id: 'contentful-management-token',
    description: 'Contentful Content Management API token (CFPAT-)',
    pattern: /\bCFPAT-[A-Za-z0-9_-]{43,}\b/g,
    replacement: '[REDACTED:contentful-management-token]',
  },
  {
    id: 'atlassian-api-token',
    description: 'Atlassian API token (ATCT, ATATT)',
    pattern: /\bAT(?:CT|ATT)[A-Za-z0-9_-]{32,}\b/g,
    replacement: '[REDACTED:atlassian-api-token]',
  },
  {
    id: 'databricks-token',
    description: 'Databricks personal access token (dapi)',
    pattern: /\bdapi[a-fA-F0-9]{32,}\b/g,
    replacement: '[REDACTED:databricks-token]',
  },
  {
    id: 'doppler-token',
    description:
      'Doppler service / personal token (dp.pt., dp.st., dp.sa., dp.scim., dp.ct., dp.audit.)',
    pattern: /\bdp\.(?:pt|st|sa|scim|ct|audit)\.[A-Za-z0-9]{40,}\b/g,
    replacement: '[REDACTED:doppler-token]',
  },
  {
    id: 'sentry-org-token',
    description: 'Sentry organization access token (sntrys_)',
    pattern: /\bsntrys_[A-Za-z0-9+/=_]{40,}\b/g,
    replacement: '[REDACTED:sentry-org-token]',
  },
  {
    id: 'dynatrace-token',
    description: 'Dynatrace API token (dt0c)',
    pattern: /\bdt0c[A-Za-z0-9._-]{30,}\b/g,
    replacement: '[REDACTED:dynatrace-token]',
  },
  {
    id: 'jfrog-api-key',
    description: 'JFrog API key (AKCp)',
    pattern: /\bAKCp[A-Za-z0-9_-]{70,}\b/g,
    replacement: '[REDACTED:jfrog-api-key]',
  },
  {
    id: 'hashicorp-tf-api-token',
    description: 'HashiCorp Terraform Cloud API token (X.atlasv1.Y)',
    pattern: /\b[A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9_-]{60,}\b/g,
    replacement: '[REDACTED:hashicorp-tf-api-token]',
  },
  {
    id: 'figma-api-token',
    description: 'Figma personal access token (figd_)',
    pattern: /\bfigd_[A-Za-z0-9_-]{40,}\b/g,
    replacement: '[REDACTED:figma-api-token]',
  },
  {
    id: 'dropbox-access-token',
    description: 'Dropbox access token (sl.)',
    pattern: /\bsl\.[A-Za-z0-9_-]{60,}\b/g,
    replacement: '[REDACTED:dropbox-access-token]',
  },
  {
    id: 'hashicorp-vault-token',
    description: 'HashiCorp Vault service / batch token (hvs., hvb.)',
    pattern: /\bhv[bs]\.[A-Za-z0-9_-]{20,}\b/g,
    replacement: '[REDACTED:hashicorp-vault-token]',
  },
  {
    id: 'sonarcloud-token',
    description: 'SonarCloud user token (squ_)',
    pattern: /\bsqu_[A-Za-z0-9]{40}\b/g,
    replacement: '[REDACTED:sonarcloud-token]',
  },
  {
    id: 'algolia-admin-api-key',
    description: 'Algolia admin API key (32 hex after ALGOLIA_ADMIN keyword)',
    pattern: /(ALGOLIA[_-]?(?:ADMIN[_-]?)?API[_-]?KEY\s*[:=]\s*)["']?[a-f0-9]{32}["']?/gi,
    replacement: '$1[REDACTED:algolia-admin-api-key]',
  },
  {
    id: 'asana-personal-access-token',
    description: 'Asana personal access token (1/digits:hex)',
    pattern: /\b1\/\d{16}:[a-f0-9]{32}\b/g,
    replacement: '[REDACTED:asana-personal-access-token]',
  },
  {
    id: 'datadog-api-key',
    description: 'Datadog API key (32 hex after DATADOG keyword)',
    pattern: /(DATADOG[_-]?(?:API[_-]?KEY|API_KEY)\s*[:=]\s*)["']?[a-f0-9]{32}["']?/gi,
    replacement: '$1[REDACTED:datadog-api-key]',
  },
  {
    id: 'datadog-app-key',
    description: 'Datadog APP key (40 hex after DATADOG keyword)',
    pattern: /(DATADOG[_-]?APP[_-]?KEY\s*[:=]\s*)["']?[a-f0-9]{40}["']?/gi,
    replacement: '$1[REDACTED:datadog-app-key]',
  },
  {
    id: 'grafana-service-account-token',
    description: 'Grafana service account token (glsa_)',
    pattern: /\bglsa_[A-Za-z0-9]{32}_[a-f0-9]{8}\b/g,
    replacement: '[REDACTED:grafana-service-account-token]',
  },
  {
    id: 'grafana-cloud-access-policy-token',
    description: 'Grafana Cloud access policy token (glc_)',
    pattern: /\bglc_[A-Za-z0-9+/=_-]{40,}\b/g,
    replacement: '[REDACTED:grafana-cloud-access-policy-token]',
  },
  {
    id: 'intercom-access-token',
    description: 'Intercom access token (dG9rOg-prefixed base64)',
    pattern: /\bdG9rOg[A-Za-z0-9+/=_-]{40,}\b/g,
    replacement: '[REDACTED:intercom-access-token]',
  },
  {
    id: 'mapbox-secret-token',
    description: 'Mapbox secret token (sk.eyJ payload)',
    pattern: /\bsk\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g,
    replacement: '[REDACTED:mapbox-secret-token]',
  },
  {
    id: 'newrelic-license-key',
    description: 'New Relic license key (40 hex ending in NRAL / NRRA)',
    pattern: /\b[a-f0-9]{36}NR[A-Z]{2}\b/g,
    replacement: '[REDACTED:newrelic-license-key]',
  },
  {
    id: 'newrelic-insert-key',
    description: 'New Relic insights insert key (NRII-)',
    pattern: /\bNRII-[A-Za-z0-9_-]{32,}\b/g,
    replacement: '[REDACTED:newrelic-insert-key]',
  },
  {
    id: 'newrelic-rest-api-key',
    description: 'New Relic REST API key (NRAK-)',
    pattern: /\bNRAK-[A-Z0-9]{27}\b/g,
    replacement: '[REDACTED:newrelic-rest-api-key]',
  },
  {
    id: 'salesforce-access-token',
    description: 'Salesforce OAuth access token (00D + ID + bang + secret)',
    pattern: /\b00D[A-Za-z0-9]{12,15}![A-Za-z0-9._]{80,}\b/g,
    replacement: '[REDACTED:salesforce-access-token]',
  },
  {
    id: 'pendo-integration-key',
    description: 'Pendo integration key (UUID after PENDO keyword)',
    pattern:
      /(PENDO[_-]?(?:INTEGRATION[_-]?)?KEY\s*[:=]\s*)["']?[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}["']?/gi,
    replacement: '$1[REDACTED:pendo-integration-key]',
  },
  {
    id: 'crowdin-access-token',
    description: 'Crowdin v2 access token (43-byte base64 ending with dot or eq)',
    pattern: /\bcrwdn_[A-Za-z0-9_-]{40,}\b/g,
    replacement: '[REDACTED:crowdin-access-token]',
  },
  {
    id: 'segment-write-key',
    description: 'Segment write key (32 alnum after SEGMENT keyword)',
    pattern: /(SEGMENT[_-]?(?:WRITE[_-]?)?KEY\s*[:=]\s*)["']?[A-Za-z0-9]{32}["']?/gi,
    replacement: '$1[REDACTED:segment-write-key]',
  },
  {
    id: 'pagerduty-api-key',
    description: 'PagerDuty API key (20 char alnum-plus after PAGERDUTY keyword)',
    pattern: /(PAGERDUTY[_-]?(?:API[_-]?)?(?:TOKEN|KEY)\s*[:=]\s*)["']?[A-Za-z0-9_+-]{20}["']?/gi,
    replacement: '$1[REDACTED:pagerduty-api-key]',
  },
  {
    id: 'launchdarkly-access-token',
    description: 'LaunchDarkly access token (api-)',
    pattern: /\bapi-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b/g,
    replacement: '[REDACTED:launchdarkly-access-token]',
  },
  {
    id: 'box-developer-token',
    description: 'Box developer token (32 char alnum after BOX keyword)',
    pattern: /(BOX[_-]?(?:DEVELOPER[_-]?)?TOKEN\s*[:=]\s*)["']?[A-Za-z0-9]{32}["']?/gi,
    replacement: '$1[REDACTED:box-developer-token]',
  },
  {
    id: 'zendesk-api-token',
    description: 'Zendesk API token (40-char alnum after ZENDESK keyword)',
    pattern: /(ZENDESK[_-]?(?:API[_-]?)?TOKEN\s*[:=]\s*)["']?[A-Za-z0-9]{40}["']?/gi,
    replacement: '$1[REDACTED:zendesk-api-token]',
  },
];
