import type { RedactionRule } from 'services/redaction/redaction.types.ts';

export const PRESERVED_TOKENS: readonly string[] = [
  '{',
  '}',
  '[',
  ']',
  ',',
  ':',
  '"',
  'user',
  'assistant',
  'system',
  'tool',
  'text',
  'image',
  'tool_use',
  'tool_result',
  'function_call',
  'tool_call',
  'message',
  'message_delta',
  'content_block_delta',
  'content_block_start',
  'content_block_stop',
  'chat.completion',
  'chat.completion.chunk',
  'stop',
  'length',
  'content_filter',
  'tool_calls',
  'end_turn',
  'max_tokens',
  'Read',
  'Write',
  'Edit',
  'Bash',
  'Glob',
  'Grep',
  'Task',
  'WebFetch',
  'WebSearch',
  'TodoWrite',
  'NotebookEdit',
  'BashOutput',
  'KillShell',
  'ExitPlanMode',
  'read_file',
  'read_file_v2',
  'write_file',
  'edit_file',
  'exec_command',
  'list_dir',
  'apply_patch',
  'apply_patch_v1',
  'shell',
  'turn_id',
  'chat_id',
  'parent_turn_id',
  'prompt_id',
  'session_id',
  'sessionId',
  'promptId',
  'composerId',
  'bubbleId',
  'composerData',
  'cwd',
  'model',
  'role',
  'type',
  'name',
  'content',
  'timestamp',
  'cli_version',
  'tokens_used',
  'inputTokens',
  'outputTokens',
  'cacheReadTokens',
  'cacheCreationTokens',
  'cache_read_input_tokens',
  'cache_creation_input_tokens',
  'finish_reason',
  'stop_reason',
  'object',
  'usage',
  'parts',
  'arguments',
  'function',
  'rowid',
  'cursorDiskKV',
];

export const PRESERVED_FIELD_CONTEXTS: readonly string[] = [
  '{"role": "user"}',
  '{"role": "assistant"}',
  '{"role": "system"}',
  '{"role": "tool"}',
  '{"type": "text"}',
  '{"type": "image"}',
  '{"type": "tool_use"}',
  '{"type": "tool_result"}',
  '{"type": "user"}',
  '{"type": "assistant"}',
  '{"type": "system"}',
  '{"type": "function_call"}',
  '{"type": "tool_call"}',
  '{"type": "message"}',
  '{"finish_reason": "stop"}',
  '{"finish_reason": "length"}',
  '{"finish_reason": "tool_calls"}',
  '{"finish_reason": "content_filter"}',
  '{"stop_reason": "end_turn"}',
  '{"stop_reason": "max_tokens"}',
  '{"stop_reason": "tool_use"}',
  '{"object": "chat.completion"}',
  '{"object": "chat.completion.chunk"}',
  '{"object": "message"}',
  '{"name": "Read"}',
  '{"name": "Write"}',
  '{"name": "Edit"}',
  '{"name": "Bash"}',
  '{"name": "Grep"}',
  '{"name": "Glob"}',
  '{"name": "Task"}',
  '{"name": "WebFetch"}',
  '{"name": "WebSearch"}',
  '{"name": "TodoWrite"}',
  '{"name": "NotebookEdit"}',
  '{"name": "BashOutput"}',
  '{"name": "ExitPlanMode"}',
  '{"name": "exec_command"}',
  '{"name": "read_file"}',
  '{"name": "read_file_v2"}',
  '{"name": "write_file"}',
  '{"name": "edit_file"}',
  '{"name": "list_dir"}',
  '{"name": "apply_patch"}',
  '{"name": "shell"}',
];

export interface PreserveAuditFinding {
  ruleId: string;
  fixture: string;
  match: string;
}

export function auditRulesAgainstFixtures(
  rules: readonly RedactionRule[],
  fixtures: readonly string[],
): PreserveAuditFinding[] {
  const findings: PreserveAuditFinding[] = [];
  for (const rule of rules) {
    for (const fixture of fixtures) {
      const matches = fixture.match(rule.pattern);
      if (matches !== null) {
        for (const m of matches) {
          findings.push({ ruleId: rule.id, fixture, match: m });
        }
      }
    }
  }
  return findings;
}
